name: DevSecOps Pipeline

on:
  push:
    branches: [ master ]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Docker Build
        run: docker build -t juice-shop .

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh

      - name: SBOM oluştur
        run: syft juice-shop -o table
