name: DevSecOps Pipeline

on:
  push:
    branches: [ master ]

jobs:
  devsecops:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # 🐳 Docker build
      - name: Docker Build
        run: docker build -t juice-shop .

      # 📦 SYFT (SBOM)
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh

      - name: Generate SBOM
        run: syft juice-shop -o table

      # 🔐 Semgrep SAST
      - name: Semgrep Scan
        uses: returntocorp/semgrep-action@v1
